### ISSUE TITLE
No module named 'src'

### ISSUE THREAD

**Issue by gr8h** [5agado/fitbit-analyzer#3]
when i run fitbit-scraper command i get No module named 'src', i'm using conda i installed all dependancies, using python 3.7

**Comment by navygit** [comment]
I get the same problem as well

**Comment by 5agado** [comment]
@gr8h , @navygit 
I assume you encounter this error because you run `setup.py` from a folder different that the main one.

If you run exactly `python setup.py install` from inside the *fitbit-analyzer* folder the scraper code should then run. I just tested on a clean env. If not, please provide more details about your setup and error message.

**Comment by navygit** [comment]
![fitbit_scraper](https://user-images.githubusercontent.com/9592892/46955514-0227e280-d08b-11e8-8f27-c5c3032a0c17.png)


yes, I am running it inside myenv3 .  python setup.py install  --> works perfectly .  But 
"  fitbit-scraper --id <your_client_id> --secret <your_client_secret> --out dump/destination/folder/path  "   or " fitbit-scraper --help "  is throwing this error

**Comment by 5agado** [comment]
@navygit Just pushed some changes. Didn't really matter during my tests, but might fix your problem. Pull the changes and try to rerun the install script.

**Comment by navygit** [comment]
@5agado  :  Thanks . That was really fast. This issue is solved now.

But, another issue with redirect URI crops up when connecting with fitbit API

![fitbit_api](https://user-images.githubusercontent.com/9592892/46958100-f3dcc500-d090-11e8-9d01-30ed4b3e1dbb.png)

**Comment by navygit** [comment]
![fibit_api_cherrypy](https://user-images.githubusercontent.com/9592892/46958181-1f5faf80-d091-11e8-9a01-8a654e735bca.png)

**Comment by 5agado** [comment]
@navygit For that you need to provide client-id and client-secret as specified in the *Usage* section of the README
