### ISSUE TITLE
sleep dashboards

### ISSUE THREAD

**Issue by navygit** [5agado/fitbit-analyzer#5]
The data scraping or data download was successful.

When I try to execute daily stats within intraday stats (the last one) 

I get : 

    name 'stats' is not defined error. 

I guess there are some lines before which have been omitted?

**Comment by 5agado** [comment]
@navygit I apologize, but the content of the notebook is not perfectly polished, is just to provide some rough guidelines on how to play around and visualize your data. At this point you should just be able to transform and plot your data based on your preference and needs.

For that specific error, for example, I guess you can just reuse whatever target stats already loaded, and change the name accordingly.

But for any error in the utils and .py files feel again free to open a new issue.
